### PR TITLE
Retry after mongo disconnection

### PR DESCRIPTION
**Pull request by ltworf**
When a mongo instance whose oplog is being tailed by the river is restarted, the river will crash. This will make river wait a while and get a new cursor to tail the oplog rather than commit suicide.

### CODE REVIEW

**Comment by matmas** [comment]
I will have a look at this

**Comment by ltworf** [comment]
To test it in vagrant you must:

1 - compile it with maven (install maven) and then run `mvn -Dmaven.test.skip=true package`
2 - in target/ or something like that there will be a jar file, copy it in vagrant and replace the river jar file with this one.
3 -  restart elastic search
4 - run nosetests
5 - restart mongo (but not elastic) this will trigger something bad in the river
6 - sleep 10 seconds
7 - run nosetests again

They should work.

**Comment by matmas** [comment]
Isn't elasticsearch-river-mongodb version 1.7.4/master supposed to work only with ES 0.90.10 ? At least according to the table https://github.com/richardwilly98/elasticsearch-river-mongodb/blob/master/README.md ?

**Comment by matmas** [comment]
It works as advertised. Apart from the things already mentioned it is good :heavy_check_mark: :accept:

**Pull request closed without merging**
